### ISSUE TITLE
[TASK] Define data model

### ISSUE THREAD

**Issue by Jarrus00** [WSU-CPTS415-ParquetParkour/Amazon-CoPurchasing#3]
_Background_:
We need a consistent paradigm for how the data will be stored and referenced.

_Problem_:
What data model will we use to represent the co-purchasing dataset, and why is it a good fit?

The [SNAP archive](https://snap.stanford.edu/data/amazon-meta.html) page indicates that the dataset was originally stored/collected as a network, so this may be the most straightforward to define and work from.

_Success Criteria_:
1. Options are identified and presented to the team.
2. Quorum is reached among the team and a data model is chosen to represent the co-purchasing dataset.
3. Specific reasoning for this design choice is documented in the wiki.
4. Wiki entry title is prepended with the tag '[MS02R01]'.

**Comment by catdennis** [comment]
![IMG_0081](https://user-images.githubusercontent.com/72167237/197354312-58deee51-61c3-4c1e-bf68-e4a98fa80f26.JPEG)

**Comment by catdennis** [comment]
Data Model:
We chose to represent our data using an entity relationship model because it is user friendly, easy to read, can be readily converted to a relational database, and conceptually describes the relation between each entity and attribute. 
The simplicity and scalability of an ER diagram allows us to use a large Amazon dataset to provide a visual starting point for our database/UI design.

**Comment by catdennis** [comment]
![Screen Shot 2022-10-22 at 7 18 58 PM](https://user-images.githubusercontent.com/72167237/197369950-3b756a0d-fa08-4d39-9832-bec61d006e2b.png)
